pipeline:
  publish-docker-image:
    image: 258875347723.dkr.ecr.us-east-1.amazonaws.com/drone-plugin-docker-ecr
    repo: 258875347723.dkr.ecr.us-east-1.amazonaws.com/reddit-nodejs
    registry: 258875347723.dkr.ecr.us-east-1.amazonaws.com
    region: us-east-1
    tag: ${DRONE_TAG}
    when:
     event: [ tag ]

  notify:
    image: plugins/slack
    channel: desktop-salon
    secrets: [ SLACK_WEBHOOK ]
    template: >
      {{#success build.status}}
        📦 Packaged <{{build.link}}|{{repo.name}}@{{build.tag}}>
      {{else}}
        🚨 *Failed* to package 📦 <{{build.link}}|{{repo.name}}@{{build.tag}}>
      {{/success}}
    when:
      status: [ success, failure ]
      event: [ tag ]
