# Pushes to master branch result in an image being built and pushed to
# Quay as quay.io/reddit/reddit-nodejs:latest.
publish:
  docker:
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: sysops@reddit.com
    repo: reddit/reddit-nodejs
    registry: quay.io
    tag: node-6.9.4
    file: Dockerfile
    when:
      branch: node-6.9.4

# These plugins are triggered after a build failure/success.
notify:
  slack:
    webhook_url: $$CI_SLACK_WEBHOOK_URL
    channel: ci-notifications
